ml-stat: deal with deleted messages
There can be "deleted" messages in lore, they are called
"d" rather than "m" (e.g. b9674655c9a972 in netdev-2).

Avoid:

    shutil.copy2(os.path.join(git_dir, 'm'), os.path.join(file_dir, str(i)))
  File "/usr/lib64/python3.12/shutil.py", line 463, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.12/shutil.py", line 260, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'netdev-2.git/m'

Signed-off-by: Jakub Kicinski <kuba@kernel.org>