ml-stat: fix check mailmap reference
Recent changes broke ml-stat --check

Traceback (most recent call last):
  File "./ml-stat.py", line 769, in <module>
    main()
  File "./ml-stat.py", line 732, in main
    ind_out = process(args, db, corp=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./ml-stat.py", line 672, in process
    name_selfcheck(ps.ppl_stat, mailmap)
                                ^^^^^^^
NameError: name 'mailmap' is not defined

Signed-off-by: Jakub Kicinski <kuba@kernel.org>